// <auto-generated />
namespace DataRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dieukhienGT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dieukhienGT));
        
        string IMigrationMetadata.Id
        {
            get { return "202101092214080_dieu-khien-GT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
