// <auto-generated />
namespace DataRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class deleteidkhuvuc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteidkhuvuc));
        
        string IMigrationMetadata.Id
        {
            get { return "202101071514243_delete-id-khuvuc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
