SET IDENTITY_INSERT [dbo].[Duongs] ON
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1001, N'An Dương Vương', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1002, N' Ao Đôi', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1003, N' Ao Sen', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1004, N' Ấp Chiến Lược', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1005, N' Bà Hom', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1006, N' Bến Lội', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1007, N' Bia Truyền Thống', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1008, N' Bình Hành', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1009, N' Bình Long', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1010, N' Bình Thành', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1011, N' Bình Trị Đông', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1012, N' Bờ sông', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1013, N' Bờ Tuyến', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1014, N' Bông Sen', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1015, N' Bùi Dương Lịch', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1016, N' Bùi Hữu Diên', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1017, N' Bùi Tư Toàn', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1018, N' Cao Tốc Trung Lương', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1019, N' Cầu Kinh', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1020, N' Cây Cám', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1021, N' Chiến Lược', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1022, N' Cống Hộp', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1023, N' Đại lộ Đông Tây', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1024, N' Đất Mới', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1025, N' Đình Nghi Xuân', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1026, N' Đình Tân Khai', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1027, N' Đỗ Bí', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1028, N' Đỗ Năng Tế', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1029, N' Đoàn Phú Tứ', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1030, N' Đường 14E', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1031, N' Đường 26 Tháng 3', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1032, N' Đường A5', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1033, N' Đường A6', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1034, N' Dương Bá Cung', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1035, N' Đường Đôi', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1036, N' Đường G1', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1037, N' Đường G7', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1038, N' Đường Kênh C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1039, N' Đường M1', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1040, N' Đường Sinco', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1041, N'2 Đường số 1', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1042, N' Đường số 10', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1043, N'2 Đường số 11', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1044, N' Đường số 11A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1045, N' Đường số 12', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1046, N' Đường số 12A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1047, N'2 Đường số 13', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1048, N'2 Đường số 13A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1049, N' Đường số 13C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1050, N'2 Đường số 14', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1051, N' Đường số 14A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1052, N' Đường số 14B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1053, N' Đường số 15', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1054, N' Đường số 16', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1055, N' Đường số 16A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1056, N' Đường số 16B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1057, N' Đường số 17', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1058, N' Đường số 17A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1059, N' Đường số 17B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1060, N' Đường số 18', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1061, N' Đường số 18A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1062, N' Đường số 18B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1063, N' Đường số 18C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1064, N' Đường số 18D', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1065, N' Đường số 18E', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1066, N' Đường số 19', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1067, N' Đường số 19A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1068, N' Đường số 19B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1069, N' Đường số 19E', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1070, N' Đường số 1A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1071, N' Đường số 1B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1072, N' Đường số 1C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1073, N' Đường số 1D', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1074, N' Đường số 2', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1075, N' Đường số 20', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1076, N' Đường số 21', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1077, N' Đường số 21A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1078, N' Đường Số 21D', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1079, N' Đường số 22', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1080, N' Đường số 23', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1081, N' Đường số 24', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1082, N' Đường số 24A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1083, N' Đường số 24B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1084, N'2 Đường số 25', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1085, N' Đường số 25A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1086, N' Đường số 26', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1087, N' Đường số 27', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1088, N' Đường số 28', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1089, N' Đường số 29', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1090, N' Đường số 2A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1091, N' Đường số 2B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1092, N' Đường số 2C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1093, N' Đường số 2D', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1094, N' Đường số 3', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1095, N' Đường số 30', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1096, N' Đường số 32', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1097, N'2 Đường số 33B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1098, N' Đường số 34', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1099, N' Đường số 36', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1100, N' Đường số 38', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1101, N' Đường số 39', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1102, N'2 Đường số 3A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1103, N' Đường số 3B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1104, N' Đường số 3C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1105, N' Đường số 4', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1106, N' Đường số 40', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1107, N' Đường số 40A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1108, N'2 Đường số 40B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1109, N' Đường số 42', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1110, N' Đường số 42A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1111, N' Đường số 43', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1112, N' Đường số 44', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1113, N' Đường số 46', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1114, N' Đường số 46A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1115, N' Đường số 47', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1116, N' Đường số 47C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1117, N' Đường số 48', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1118, N' Đường số 48A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1119, N' Đường số 48B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1120, N' Đường số 49', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1121, N' Đường số 49A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1122, N' Đường số 49B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1123, N' Đường số 49C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1124, N' Đường số 4A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1125, N' Đường số 4C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1126, N' Đường số 5', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1127, N' Đường số 50', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1128, N' Đường số 504', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1129, N' Đường số 50A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1130, N' Đường số 50B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1131, N'2 Đường số 50C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1132, N' Đường số 50D', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1133, N' Đường số 51', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1134, N' Đường số 52', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1135, N' Đường số 52A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1136, N' Đường số 52B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1137, N' Đường số 53', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1138, N' Đường số 532', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1139, N' Đường số 53A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1140, N' Đường số 53C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1141, N' Đường số 53D', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1142, N' Đường số 54', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1143, N' Đường số 54A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1144, N' Đường số 55', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1145, N' Đường số 55A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1146, N' Đường số 57', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1147, N' Đường số 57A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1148, N' Đường số 57B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1149, N' Đường số 57C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1150, N' Đường số 59D', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1151, N' Đường số 5A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1152, N'2 Đường số 5B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1153, N' Đường số 5C', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1154, N'2 Đường số 5D', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1155, N' Đường số 5E', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1156, N' Đường số 5F', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1157, N'2 Đường số 6', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1158, N' Đường số 6A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1159, N' Đường số 7', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1160, N' Đường số 7A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1161, N' Đường số 7B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1162, N' Đường số 8', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1163, N' Đường số 8B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1164, N' Đường số 9', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1165, N' Đường số 9A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1166, N' Đường số 9B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1167, N' Đường Trung Tâm', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1168, N' Dương Tự Quán', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1169, N' Gò Xoài', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1170, N' Hồ Học Lãm', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1171, N' Hồ Văn Long', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1172, N' Hoàng Hưng', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1173, N' Hoàng Văn Hợp', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1174, N' Hùng Vương', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1175, N' Hương lộ 13', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1176, N' Hương lộ 2', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1177, N' Hương lộ 3', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1178, N' Hương Lộ 5', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1179, N' Hương lộ 80', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1180, N' Kênh Nước Đen', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1181, N' Khiếu Năng Tỉnh', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1182, N' Khu Y Tế Kỹ Thuật Cao', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1183, N' Kinh Dương Vương', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1184, N' Lâm Hoành', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1185, N' Lê Cơ', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1186, N' Lê Công Phép', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1187, N' Lê Đình Cẩn', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1188, N' Lê Đình Dương', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1189, N' Lê Lợi', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1190, N' Lê Ngung', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1191, N' Lê Tấn Bê', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1192, N' Lê Thúc Hoạch', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1193, N' Lê Trọng Tấn', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1194, N' Lê Văn Quế', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1195, N' Lê Văn Quới', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1196, N' Liên khu 10-11', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1197, N' Liên Khu 1-6', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1198, N' Liên khu 16-18', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1199, N' LIÊN KHU 2-10', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1200, N'2 Liên Khu 2-5', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1201, N' Liên khu 4-5', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1202, N' Liên Khu 5', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1203, N'3 Liên Khu 5-11-12', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1204, N' Liên khu 5-6', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1205, N' Liên Khu 7-13', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1206, N' Liên Khu 8-9', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1207, N' Lộ Tẻ', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1208, N' Lô Tư', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1209, N' Lý Chiêu Hoàng', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1210, N' Lý Thánh Tông', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1211, N' Mã Lò', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1212, N' Miếu Bình Đông', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1213, N' Miếu Gò Xoài', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1214, N' Nghi Xuân', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1215, N' Ngô Y Linh', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1216, N' Nguyễn Cửu Phú', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1217, N' Nguyễn Đình Kiên', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1218, N' Nguyễn Hới', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1219, N' Nguyễn Hữu Cảnh', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1220, N' Nguyễn Quý Yêm', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1221, N' Nguyễn Sơn', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1222, N' Nguyễn Thị Tú', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1223, N' Nguyễn Thức Đường', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1224, N' Nguyễn Thức Tự', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1225, N' Nguyễn Triệu Luật', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1226, N' Nguyễn Trọng Chí', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1227, N' Nguyễn Trọng Trí', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1228, N' Nguyễn Văn Cừ', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1229, N' Phạm Bành', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1230, N' Phạm Đăng Giảng', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1231, N' Phan Anh', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1232, N' Phan Cát Tựu', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1233, N' Phan Đình Thông', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1234, N' Phan Văn Năm', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1235, N' Phùng Tá Chu', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1236, N' Quốc Lộ 1A', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1237, N' Sông Suối', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1238, N' Sông Tắc', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1239, N' Tạ Mỹ Duật', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1240, N' Tạ Quang Bửu', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1241, N' Tân Hòa Đông', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1242, N' Tân Khai', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1243, N' Tân Kỳ Tân Quý', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1244, N' Tân Sơn Nhì', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1245, N' Tân Tạo', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1246, N' Tây Lân', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1247, N' Tên Lửa', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1248, N' Thạch Lam', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1249, N' Thăng Long', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1250, N' Thoại Ngọc Hầu', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1251, N' Tỉnh Lộ 10', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1252, N' Tỉnh Lộ 13', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1253, N' Tỉnh lộ 8', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1254, N' Trần Đại Nghĩa', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1255, N' Trần Thanh Mai', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1256, N' Trần Thanh Mại', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1257, N' Trương Phước Phan', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1258, N' Vành Đai Trong', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1259, N' Vĩnh Lộc', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1260, N' Vĩnh Lộc B', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1261, N' Võ Văn Kiệt', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1262, N' Võ Văn Vân', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1263, N' Vũ Hữu', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1264, N' Vương Văn Huống', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1265, N' Xa Lộ Đại Hàn', 1)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1266, N'Bắc Bình', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1267, N' Bạch Đằng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1268, N' Bình Lợi', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1269, N' Bình Quới', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1270, N' Bùi Đình Túy', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1271, N' Bùi Hữu Nghĩa', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1272, N' Chu Văn An', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1273, N' Công Trường Hòa Bình', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1274, N' Công Trường Tự Do', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1275, N' Cửu Long', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1276, N' Điện Biên Phủ', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1277, N' Diên Hồng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1278, N' Đinh Bộ Lĩnh', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1279, N' Đinh Tiên Hoàng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1280, N' Đống Đa', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1281, N' Đường D1', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1282, N' Đường D2', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1283, N' Đường D3', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1284, N' Đường D4', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1285, N' Đường D5', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1286, N' Đường số 1', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1287, N' Đường số 10', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1288, N' Đường số 12AB', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1289, N' Đường số 14', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1290, N' Đường số 16', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1291, N' Đường số 18', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1292, N' Đường số 2', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1293, N' Đường số 3', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1294, N' Đường số 304', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1295, N' Đường số 4', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1296, N' Đường số 48', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1297, N'2 Đường số 5', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1298, N' Đường số 6', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1299, N' Đường số 8', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1300, N' Đường số 82', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1301, N' Đường Trục', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1302, N' Hồ Xuân Hương', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1303, N' Hoàng Hoa Thám', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1304, N' Hồng Bàng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1305, N' Huỳnh Đình Hai', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1306, N' Huỳnh Khương An', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1307, N' Huỳnh Mẫn Đạt', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1308, N' Huỳnh Tá Bang', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1309, N' Huỳnh Thúc Kháng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1310, N' Huỳnh Tịnh Của', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1311, N' Lái Thiêu', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1312, N' Lam Sơn', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1313, N' Lê Hoàng Phái', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1314, N' Lê Lợi', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1315, N' Lê Quang Định', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1316, N' Lê Trực', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1317, N' Lê Tự Tài', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1318, N' Lương Ngọc Quyến', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1319, N' Mai Xuân Thưởng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1320, N' Mê Linh', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1321, N' Miếu Nổi', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1322, N' Ngô Đức Kế', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1323, N' Ngô Nhân Tịnh', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1324, N' Ngô Tất Tố', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1325, N' Nguyễn An Ninh', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1326, N' Nguyễn Bỉnh Khiêm', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1327, N' Nguyễn Công Hoan', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1328, N' Nguyễn Công Trứ', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1329, N' Nguyễn Cửu Vân', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1330, N' Nguyễn Duy', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1331, N'2 Nguyên Hồng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1332, N' Nguyễn Hữu Cảnh', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1333, N' Nguyễn Huy Lượng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1334, N' Nguyễn Huy Tưởng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1335, N' Nguyễn Khuyến', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1336, N' Nguyễn Kiệm', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1337, N' Nguyễn Lâm', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1338, N' Nguyễn Ngọc Phương', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1339, N' Nguyễn Thái Học', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1340, N' Nguyễn Thái Sơn', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1341, N' Nguyễn Thị Tú', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1342, N' Nguyễn Thiện Thuật', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1343, N' Nguyễn Thượng Hiền', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1344, N' Nguyễn Trọng Tuyển', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1345, N' Nguyễn Trung Trực', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1346, N' Nguyễn Văn Đậu', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1347, N' Nguyễn Văn Lạc', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1348, N' Nguyễn Xí', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1349, N' Nguyễn Xuân Ôn', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1350, N' Nơ Trang Long', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1351, N' Phạm Văn Đồng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1352, N' Phạm văn hai', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1353, N' Phạm Viết Chánh', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1354, N' Phan Bội Châu', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1355, N' Phan Chu Trinh', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1356, N' Phan Đăng Lưu', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1357, N' Phan Đình Phùng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1358, N' Phan Huy Ôn', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1359, N' Phan Văn Hân', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1360, N' Phan Văn Trị', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1361, N' Phan Xích Long', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1362, N' Phó Đức Chính', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1363, N' Phú Mỹ', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1364, N' Quốc Lộ 13', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1365, N' Tầm Vu', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1366, N' Tăng Bạt Hổ', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1367, N'2 Thanh Đa', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1368, N' Thiên Hộ Dương', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1369, N' Trần Bình Trọng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1370, N' Trần Kế Xương', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1371, N' Trần Quốc Tuấn', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1372, N' Trần Quý Cáp', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1373, N' Trần Văn Kỷ', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1374, N' Trịnh Hoài Đức', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1375, N' Trục 30m', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1376, N' Trường Sa', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1377, N' Ung Văn Khiêm', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1378, N' Vạn Kiếp', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1379, N' Văn Thánh Bắc', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1380, N' Võ Duy Ninh', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1381, N' Võ Thành Trang', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1382, N' Võ Trường Toản', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1383, N' Vũ Huy Tấn', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1384, N' Vũ Ngọc Phan', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1385, N' Vũ Tùng', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1386, N' Xô Viết Nghệ Tĩnh', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1387, N' Yên Đỗ', 2)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1388, N'An Hội', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1389, N' An Nhơn', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1390, N' Bùi Quang Là', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1391, N' Cây Trâm', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1392, N' Đỗ Thúc Tịnh', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1393, N' Đường 26 Tháng 3', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1394, N' Dương Quảng Hàm', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1395, N' Đường số 1', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1396, N' Đường số 10', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1397, N' Đường số 11', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1398, N'2 Đường số 12', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1399, N' Đường số 13', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1400, N' Đường số 14', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1401, N' Đường số 15', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1402, N' Đường số 17', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1403, N' Đường số 18', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1404, N' Đường số 19', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1405, N' Đường số 2', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1406, N'2 Đường số 20', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1407, N'2 Đường số 21', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1408, N' Đường số 22', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1409, N' Đường số 23', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1410, N' Đường số 24', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1411, N' Đường số 25', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1412, N' Đường số 27', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1413, N'2 Đường số 28', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1414, N' Đường số 29', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1415, N' Đường số 3', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1416, N' Đường số 30', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1417, N' Đường số 31', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1418, N' Đường số 32', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1419, N' Đường số 35', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1420, N' Đường số 38', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1421, N' Đường số 4', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1422, N' Đường số 43', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1423, N' Đường số 45', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1424, N' Đường số 46', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1425, N' Đường số 47', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1426, N'2 Đường số 5', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1427, N' Đường số 50', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1428, N' Đường số 51', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1429, N' Đường số 53', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1430, N' Đường số 55', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1431, N' Đường Số 56', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1432, N' Đường số 57', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1433, N' Đường số 58', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1434, N' Đường số 59', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1435, N'2 Đường số 6', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1436, N' Đường số 7', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1437, N' Đường số 8', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1438, N' Đường số 9', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1439, N' Hạnh Thông', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1440, N' Hạnh Thông Tây', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1441, N' Hoàng Hoa Thám', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1442, N' Hoàng Minh Giám', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1443, N' Huỳnh Khương An', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1444, N' Huỳnh Văn Nghệ', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1445, N' Lê Đức Thọ', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1446, N' Lê Hoàng Phái', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1447, N' Lê Lai', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1448, N' Lê Lợi', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1449, N' Lê Quang Định', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1450, N' Lê Thị Hồng', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1451, N' Lê Văn Thọ', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1452, N' Lê Văn Trị', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1453, N' Lương Ngọc Quyến', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1454, N' Lý Thường Kiệt', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1455, N' Nguyễn Bỉnh Khiêm', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1456, N' Nguyễn Du', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1457, N' Nguyễn Duy Cung', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1458, N' Nguyên Hồng', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1459, N' Nguyễn Hữu Thọ', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1460, N' Nguyễn Huy Điển', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1461, N' Nguyễn Kiệm', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1462, N' Nguyễn Oanh', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1463, N' Nguyễn Thái Sơn', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1464, N' Nguyễn Thị Nhỏ', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1465, N' Nguyễn Thượng Hiền', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1466, N' Nguyễn Tư Giản', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1467, N' Nguyễn Tuân', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1468, N' Nguyễn Văn Bảo', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1469, N' Nguyễn Văn Công', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1470, N' Nguyễn Văn Dung', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1471, N' Nguyễn Văn Lượng', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1472, N' Nguyễn Văn Nghi', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1473, N' Phạm Huy Thông', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1474, N' Phạm Ngũ Lão', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1475, N' Phạm Văn Bạch', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1476, N' Phạm Văn Chiêu', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1477, N' Phạm Văn Đồng', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1478, N' Phan Huy Ích', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1479, N' Phan Văn Trị', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1480, N' Phùng Văn Cung', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1481, N' Quang Trung', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1482, N' Tân Sơn', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1483, N' Tân Thọ', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1484, N' Thích Bửu Đăng', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1485, N' Thiên Hộ Dương', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1486, N' Thống Nhất', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1487, N' Thông Tây Hội', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1488, N' Tô Ngọc Vân', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1489, N' Trần Bá Giao', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1490, N' Trần Bình Trọng', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1491, N' Trần Phú Cương', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1492, N' Trần Quốc Tuấn', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1493, N' Trần Thị Nghĩ', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1494, N' Trưng Nữ Vương', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1495, N' Trương Đăng Quế', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1496, N' Trương Minh Giảng', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1497, N' Trương Minh Ký', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1498, N' Tú Mỡ', 3)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1499, N'Bạch Đằng', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1500, N'Cao Thắng', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1501, N'Cầm Bá Thước', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1502, N'Cô Bắc', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1503, N'Cô Giang', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1504, N'Cù Lao', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1505, N'Đào Duy Anh', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1506, N'Đào Duy Từ', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1507, N'Đặng Thai Mai', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1508, N'Đặng Văn Ngữ', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1509, N'Đoàn Thị Điểm', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1510, N'Hoa Cau', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1511, N'Hoa Cúc', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1512, N'Hoa Đào', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1513, N'Hoa Hồng', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1514, N'Hoa Huệ', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1515, N'Hoa Lan', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1516, N'Hoa Mai', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1517, N'Hoa Phượng', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1518, N'Hoa Sứ', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1519, N'Ký Con', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1520, N'Hoàng Diệu', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1521, N'Hoàng Minh Giám', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1522, N'Hoàng Văn Thụ', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1523, N'Hồ Văn Huê', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1524, N'Hồng Hà', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1525, N'Huỳnh Văn Bánh', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1526, N'Lam Sơn', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1527, N'Lê Tư Tài', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1528, N'Lê Văn Sĩ', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1529, N'Mai Văn Ngọc', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1530, N'Mai Văn Nguyễn', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1531, N'Nguyễn Công Hoan', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1532, N'Nguyễn Đình Chính', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1533, N'Nguyễn Đình Chiểu', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1534, N'Nguyễn Kiệm', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1535, N'Nguyễn Thái Sơn', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1536, N'Nguyễn Thị Huỳnh', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1537, N'Nguyễn Thượng Hiền', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1538, N'Nguyễn Trọng Tuyển', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1539, N'Nguyễn Văn Đậu', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1540, N'Nguyễn Văn Trỗi', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1541, N'Nhiêu Tứ', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1542, N'Nội Bộ', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1543, N'Phan Đăng Lưu', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1544, N'Phan Đình Phùng', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1545, N'Phan Tây Hồ', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1546, N'Phan Xích Long', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1547, N'Phổ Quang', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1548, N'Phùng Văn Cung', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1549, N'Tân Cảnh', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1550, N'Thích Quảng Đức', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1551, N'Trần Cao Vân', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1552, N'Trần Hữu Trang', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1553, N'Trần Kế Xương', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1554, N'Trần Khắc Chân', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1555, N'Trần Quang Diệu', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1556, N'Trương Đăng Quế', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1557, N'Trương Quốc Dung', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1558, N'Trường Sa', 4)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1559, N'Ấp Bắc', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1560, N' Âu Cơ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1561, N' Ba Gia', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1562, N' Ba Vân', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1563, N' Ba Vì', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1564, N' Bắc Hải', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1565, N' Bạch Đằng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1566, N' Bạch Đằng 1', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1567, N' Bạch Đằng 2', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1568, N' Bạch Mã', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1569, N' Bành Văn Trân', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1570, N' Bàu Bàng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1571, N' Bàu Cát', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1572, N' Bàu Cát 1', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1573, N' Bàu cát 2', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1574, N' Bàu Cát 3', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1575, N' Bàu Cát 4', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1576, N' Bàu Cát 5', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1577, N' Bàu Cát 6', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1578, N' Bàu Cát 7', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1579, N' Bàu Cát 8', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1580, N' Bàu Cát 9', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1581, N' Bàu Cát Đôi', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1582, N' Bảy Hiền', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1583, N' Bế Văn Đàn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1584, N' Bến Cát', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1585, N' Bình Giã', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1586, N' Bùi Thế Mỹ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1587, N' Bùi Thị Xuân', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1588, N' Bùi Tư Toàn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1589, N' Ca Văn Thỉnh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1590, N' Cách Mạng Tháng 8', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1591, N' Cầu Cống Lở', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1592, N' Chấn Hưng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1593, N' Châu Vĩnh Tế', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1594, N' Chí Công', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1595, N' Chí Linh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1596, N' Chử Đồng Tử', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1597, N' Cộng Hòa', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1598, N' Cống Lở', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1599, N' Cù Chính Lan', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1600, N' Cửu Long', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1601, N' Đại Nghĩa', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1602, N' Dân Trí', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1603, N' Đặng Lộ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1604, N' Đặng Minh Trứ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1605, N' Đất Thánh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1606, N' Đinh Điền', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1607, N' Đồ Sơn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1608, N' Dọc Bờ Kênh Nhiêu Lộc', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1609, N' Đống Đa', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1610, N' Đồng Đen', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1611, N' Đông Hồ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1612, N' Đồng Khởi', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1613, N' Đồng Nai', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1614, N' Đông Sơn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1615, N' Đồng Xoài', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1616, N' Đường 27 Tháng 3', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1617, N' Đường A4', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1618, N' Đường B1', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1619, N' Đường B6', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1620, N' Đường C1', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1621, N' Đường C12', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1622, N' Đường C18', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1623, N' Đường C2', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1624, N' Đường C22', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1625, N' Đường C27', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1626, N' Đường C3', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1627, N' Đường D10', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1628, N' Đường D50', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1629, N' Đường D51', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1630, N' Đường D52', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1631, N'2 Đường số 1', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1632, N' Đường số 175', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1633, N' Đường số 2', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1634, N' Đường số 3', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1635, N' Đường số 4', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1636, N' Đường số 5', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1637, N' Đường số 6', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1638, N' Đường số 7', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1639, N' Dương Văn Dương', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1640, N' Dương Vân Nga', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1641, N' Duy Tân', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1642, N' Giải Phóng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1643, N' Gò Cẩm Đệm', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1644, N' Gò Dầu', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1645, N' Hà Bá Tường', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1646, N' Hát Giang', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1647, N' Hậu Giang', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1648, N' Hiệp Nhất', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1649, N' Hồ Đắc Di', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1650, N' Hòa Bình', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1651, N' Hòa Hiệp', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1652, N' Hoàng Bật Đạt', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1653, N' Hoàng Hoa Thám', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1654, N' Hoàng Kế Viêm', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1655, N' Hoàng Sa', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1656, N' Hoàng Văn Thụ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1657, N' Hoàng Việt', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1658, N' Hồng Hà', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1659, N' Hồng Lạc', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1660, N' Hưng Hóa', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1661, N' Hương lộ 2', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1662, N' Huỳnh Lan Khanh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1663, N' Huỳnh Tịnh Của', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1664, N' Huỳnh Văn Nghệ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1665, N' Kênh Nhiêu Lộc', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1666, N' Khai Quang', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1667, N' Khai Trí', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1668, N' Khuông Việt', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1669, N' Lạc Long Quân', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1670, N' Lam Sơn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1671, N' Lê Bình', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1672, N' Lê Duy Nhuận', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1673, N' Lê Lai', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1674, N' Lê Lợi', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1675, N' Lê Minh Xuân', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1676, N' Lê Ngân', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1677, N' Lê Tấn Quốc', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1678, N' Lê Trọng Tấn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1679, N' Lê Trung Nghĩa', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1680, N' Lê Văn Huân', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1681, N' Lê Văn Sỹ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1682, N' Lộc Hưng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1683, N' Lộc Vinh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1684, N' Long Hưng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1685, N' Lương Thế Vinh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1686, N' Lưu Nhân Chú', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1687, N' Lý Thường Kiệt', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1688, N' Mai Lão Bạng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1689, N' Năm Châu', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1690, N' Nghĩa Hòa', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1691, N' Nghĩa Hưng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1692, N' Nghĩa Phát', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1693, N' Ngô Bệ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1694, N' Ngô Thị Thu Minh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1695, N' Ngự Bình', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1696, N' Nguyễn Bá Tòng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1697, N' Nguyễn Bá Tuyển', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1698, N' Nguyễn Bặc', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1699, N' Nguyễn Cảnh Dị', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1700, N' Nguyễn Chánh Sắt', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1701, N' Nguyễn Đình Khơi', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1702, N' Nguyễn Đức Thuận', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1703, N' Nguyễn Hiến Lê', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1704, N' Nguyễn Hồng Đào', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1705, N' Nguyễn Minh Hoàng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1706, N' Nguyễn Phúc Chu', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1707, N' Nguyễn Quang Bích', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1708, N' Nguyễn Sơn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1709, N' Nguyễn Sỹ Sách', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1710, N' Nguyễn Thái Bình', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1711, N' Nguyễn Thanh Tuyền', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1712, N' Nguyễn Thế Lộc', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1713, N' Nguyễn Thị Nhỏ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1714, N' Nguyễn Trọng Lội', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1715, N' Nguyễn Trọng Tuyển', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1716, N' Nguyễn Tử Nha', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1717, N' Nguyễn Văn Mại', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1718, N' Nguyễn Văn Trỗi', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1719, N' Nguyễn Văn Vĩ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1720, N' Nguyễn Văn Vĩnh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1721, N' Nguyễn Xuân Khoát', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1722, N' Nhất Chi Mai', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1723, N' Ni Sư Huỳnh Liên', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1724, N' Núi Thành', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1725, N' Phạm Cự Lượng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1726, N' Phạm Hồng Thái', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1727, N' Phạm Phú Thứ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1728, N' Phạm Văn Bạch', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1729, N' Phạm văn hai', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1730, N' Phan Anh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1731, N' Phan Bá Phiến', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1732, N' Phan Đình Giót', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1733, N' Phan Huy Ích', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1734, N' Phan Sào Nam', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1735, N' Phan Thúc Duyện', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1736, N' Phan Văn Lâu', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1737, N' Phan Văn Sửu', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1738, N' Phổ Quang', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1739, N' Phú Hoà', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1740, N' Phú Lộc', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1741, N' Quách Văn Tuấn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1742, N' Quảng Hiền', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1743, N' Sầm Sơn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1744, N' Sao Mai', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1745, N' Sơn Cang', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1746, N' Sơn Hưng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1747, N' Sông Đà', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1748, N' Sông Đáy', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1749, N' Sông Nhuệ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1750, N' Sông Thao', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1751, N' Sông Thương', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1752, N' Tân Canh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1753, N' Tân Châu', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1754, N' Tân Hải', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1755, N' Tân Khai', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1756, N' Tân Kỳ Tân Quý', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1757, N' Tân Lập', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1758, N' Tân Phước', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1759, N' Tân Sơn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1760, N' Tân Sơn Hòa', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1761, N' Tân Sơn Nhì', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1762, N' Tân Tạo', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1763, N' Tân Thọ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1764, N' Tân Tiến', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1765, N' Tân Trang', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1766, N' Tân Trụ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1767, N' Tản Viên', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1768, N' Tân Xuân', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1769, N' Thái Thị Nhạn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1770, N' Thân Nhân Trung', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1771, N' Thăng Long', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1772, N' Thành Mỹ', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1773, N' Thép Mới', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1774, N' Thích Minh Nguyệt', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1775, N' Thiên Phước', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1776, N' Thủ Khoa Huân', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1777, N' Tiền Giang', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1778, N' Tống Văn Hên', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1779, N' Trà Khúc', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1780, N' Trần Đình Trọng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1781, N' Trần Mai Ninh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1782, N' Trần Quốc Hoàn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1783, N' Trần Thái Tông', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1784, N' Trần Thánh Tông', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1785, N' Trần Triệu Luật', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1786, N' Trần Văn Đang', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1787, N' Trần Văn Danh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1788, N' Trần Văn Dư', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1789, N' Trần Văn Hoàng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1790, N' Trần Văn Quang', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1791, N' Trịnh Đình Thảo', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1792, N' Trung Lang', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1793, N' Trường Chinh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1794, N' Trương Công Định', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1795, N' Trương Hoàng Thanh', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1796, N' Trường Sa', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1797, N' Trường Sơn', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1798, N' Tự Cường', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1799, N' Tứ Hải', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1800, N' Tự Lập', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1801, N' Út Tịch', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1802, N' Văn Chung', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1803, N' Vân Côi', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1804, N' Võ Thành Trang', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1805, N' Vườn Lan', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1806, N' Xuân Diệu', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1807, N' Xuân Hồng', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1808, N' Yên Thế', 5)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1809, N'Âu Cơ', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1810, N' Âu Dương Lân', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1811, N' Bác Ái', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1812, N' Bình Long', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1813, N' Bờ Bao Tân Thắng', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1814, N' Bùi Cẩm Hổ', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1815, N' Bùi Thế Mỹ', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1816, N' Bùi Xuân Phái', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1817, N' Cách Mạng', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1818, N' Cách Mạng Tháng 8', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1819, N' Cao thế', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1820, N' Cao Văn ngọc', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1821, N' Cầu Xéo', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1822, N' Cây Keo', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1823, N' Chân Lý', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1824, N' Chế Lan Viên', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1825, N' Chu Thiên', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1826, N' Chu Văn An', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1827, N' Cộng Hòa 3', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1828, N' Đàm Thận Huy', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1829, N' Dân Chủ', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1830, N' Dân Tộc', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1831, N' Điện Cao Thế', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1832, N' Diệp Minh Châu', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1833, N' Đinh Liệt', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1834, N' Đỗ Bí', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1835, N' Đỗ Công Tường', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1836, N' Đô Đốc Chấn', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1837, N' Đô Đốc Lộc', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1838, N' Đô Đốc Long', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1839, N' Đô Đốc Thủ', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1840, N' Đỗ Đức Dục', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1841, N' Đỗ Nhuận', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1842, N' Đỗ Thị Tâm', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1843, N' Đỗ Thừa Luông', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1844, N' Đỗ Thừa Tự', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1845, N' Đoàn Giỏi', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1846, N' Đoàn Hồng Phước', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1847, N' Đoàn Kết', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1848, N' Độc Lập', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1849, N' Đường 30 Tháng 4', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1850, N' Đường B', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1851, N' Đường B2', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1852, N' Đường B3', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1853, N' Đường C1', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1854, N' Đường C4', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1855, N' Đường C4A', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1856, N' Đường C5', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1857, N' Đường C6', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1858, N' Đường C6A', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1859, N' Đường C7', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1860, N' Đường C8', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1861, N' Đường CC1', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1862, N' Đường CC2', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1863, N' Đường CC3', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1864, N' Đường CC4', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1865, N' Đường CC5', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1866, N' Đường CN 11', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1867, N' Đường CN 13', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1868, N' Đường CN 6', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1869, N' Đường CN1', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1870, N' Đường CN11', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1871, N' Đường CN13', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1872, N' Đường CN6', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1873, N' Đường D10', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1874, N' Đường D11', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1875, N' Đường D12', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1876, N' Đường D13', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1877, N' Đường D14A', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1878, N' Đường D14B', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1879, N' Đường D15', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1880, N' Đường D16', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1881, N' Đường D9', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1882, N' Đường DC1', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1883, N' Đường DC11', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1884, N' Đường DC13', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1885, N' Đường DC3', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1886, N' Đường DC4', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1887, N' Đường DC5', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1888, N' Đường DC7', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1889, N' Đường DC9', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1890, N' Dương Đức Hiền', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1891, N' Đường Kênh 19/5', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1892, N' Dương Khuê', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1893, N' Đường M5', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1894, N' Đường S1', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1895, N' Đường S11', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1896, N' Đường S3', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1897, N' Đường S5', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1898, N' Đường S7', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1899, N' Đường S9', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1900, N' Đường số 1', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1901, N' Đường số 18', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1902, N' Đường số 19', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1903, N' Đường số 2', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1904, N' Đường số 27', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1905, N' Đường T1', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1906, N' Đường T4A', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1907, N' Đường T4B', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1908, N' Đường T5', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1909, N' Đường T6', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1910, N' Đường T8', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1911, N' Dương Thiệu Tước', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1912, N' Dương Văn Dương', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1913, N' Gò Dầu', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1914, N' Gò Xoài', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1915, N' Hàn Mạc Tử', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1916, N' Hiền Vương', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1917, N' Hồ Đắc Di', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1918, N' Hồ Ngọc Cẩn', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1919, N' Hoa Bằng', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1920, N' Hòa Bình', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1921, N' Hoàng Ngọc Phách', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1922, N' Hoàng Thiều Hoa', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1923, N' Hoàng Văn Hòe', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1924, N' Hoàng Xuân Nhị', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1925, N' Hương lộ 3', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1926, N' Huỳnh Thiện Lộc', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1927, N' Huỳnh Văn Chính', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1928, N' Huỳnh Văn Một', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1929, N' Ích Thiện', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1930, N' Kênh 19 Tháng 5', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1931, N' Kênh Nước Đen', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1932, N' Kênh Tân Hóa', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1933, N' Khuông Việt', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1934, N' Lê Cảnh Tuân', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1935, N' Lê Cao Lãng', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1936, N' Lê Đại', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1937, N' Lê Đình Thám', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1938, N' Lê Đình Thụ', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1939, N' Lê Khôi', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1940, N' Lê Lâm', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1941, N' Lê Lăng', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1942, N' Lê Liễu', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1943, N' Lê Lộ', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1944, N' Lê Lư', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1945, N' Lê Ngã', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1946, N' Lê Niệm', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1947, N' Lê Quang Chiểu', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1948, N' Lê Quốc Trinh', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1949, N' Lê Sao', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1950, N' Lê Sát', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1951, N' Lê Thận', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1952, N' Lê Thiệt', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1953, N' Lê Thúc Hoạch', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1954, N' Lê Trọng Tấn', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1955, N' Lê Trúc', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1956, N' Lê Trung Đình', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1957, N' Lê Văn Phan', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1958, N' Lê Vĩnh Hòa', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1959, N' Lương Đắc Bằng', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1960, N' Lương Minh Nguyệt', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1961, N' Lương Thế Vinh', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1962, N' Lương Trúc Đàm', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1963, N' Lưu Chí Hiếu', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1964, N' Lũy Bán Bích', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1965, N' Lý Thái Tông', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1966, N' Lý Thánh Tông', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1967, N' Lý Tuệ', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1968, N' Ngô Quyền', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1969, N' Nguyễn Bá Tòng', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1970, N' Nguyễn Chích', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1971, N' Nguyễn Cửu Đàm', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1972, N' Nguyễn Cửu Phú', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1973, N' Nguyễn Đỗ Cung', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1974, N' Nguyễn Dữ', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1975, N' Nguyễn Hảo Vĩnh', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1976, N' Nguyễn Hậu', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1977, N' Nguyễn Hữu Dật', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1978, N' Nguyễn Hữu Tiến', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1979, N' Nguyễn Lộ Trạch', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1980, N' Nguyễn Lý', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1981, N' Nguyễn Minh Châu', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1982, N' Nguyễn Mỹ Ca', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1983, N' Nguyễn Ngọc Nhựt', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1984, N' Nguyễn Nhữ Lãm', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1985, N' Nguyễn Quang Diệu', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1986, N' Nguyễn Quý Anh', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1987, N' Nguyễn Sơn', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1988, N' Nguyễn Súy', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1989, N' Nguyễn Thái Học', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1990, N' Nguyễn Thế Truyện', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1991, N' Nguyễn Thiện Lâu', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1992, N' Nguyễn Trường Tộ', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1993, N' Nguyễn Uẩn Sang', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1994, N' Nguyễn Văn Dưỡng', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1995, N' Nguyễn Văn Ngọc', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1996, N' Nguyễn Văn Săng', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1997, N' Nguyễn Văn Tố', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1998, N' Nguyễn Văn Vịnh', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (1999, N' Nguyễn Xuân Khoát', 6)
INSERT INTO [dbo].[Duongs] ([Id], [TenDuong], [KhuVuc_Id]) VALUES (2000, N' Phạm Ngọc', 6)
SET IDENTITY_INSERT [dbo].[Duongs] OFF
